### ISSUE TITLE
font-awesome - css inlined in the html

### ISSUE THREAD

**Issue by awronski** [nuxt-community/modules#107]
Hi!

when using font-awesome module with `nuxt rc.3` the whole css file is inlined for every new request.
So there is no advantage of the browser cache.

I am not sure if this is a nuxt problem or just module configuration?

Thanks in advance,

**Comment by pi0** [comment]
Hi. Did you enabled `build: { extractCss:true }` per project?

**Comment by awronski** [comment]
No, i use plain nuxt-starter template.

```js
module.exports = {
  head: {
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      { rel: 'stylesheet', href: '/bootstrap4a6.min.css' }
    ]
  },
  css: ['~assets/main.styl'],
  loading: { color: '#3B8070' },
  modules: [
    [ '@nuxtjs/font-awesome' ]
  ],
}
```

Html output:
```html
[...]
<style data-vue-ssr-id="49bde2da:0">/*!
--
  | *  Font Awesome 4.7.0 by @davegandy - http://fontawesome.io - @fontawesome
  | *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
  | */
  | /* FONT PATH
  | * -------------------------- */
  | @font-face {
  | font-family: 'FontAwesome';
[...]
```

**Comment by pi0** [comment]
Opps, the Correct key was `extractCSS`, sorry mate!

**Comment by awronski** [comment]
The same result with `extractCSS` :(

**Comment by pimlie** [comment]
Are you running in dev mode or in production mode? `extractCSS` does not work in `dev` mode so you can use hot-reloading.

**Comment by awronski** [comment]
@pimlie thank you! Your are right. It is working only for build.

Btw default mode is `extractCSS: false`.
There is no info about this option in the docs.
