### ISSUE TITLE
How to use $axios in a JS module

### ISSUE THREAD

**Issue by TheDeveloperTom** [nuxt-community/modules#112]
How to get access to the $axios instance in a JS module, that has to make a request.

The option to pass the $axios instance from a vuex action is not suitable in my case.

So, is it real at all?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/modules/issues/c61">#c61</a>)</em></sub></div>

**Comment by pi0** [comment]
Fixed with vuex@2.4.1

**Comment by TheDeveloperTom** [comment]
And, how is it fixed? Am I able to get access to the $axios instance in a js module of my project?

**Comment by pi0** [comment]
@TheDeveloperTom Please take a look at store section in axios docs, there is no longer needed to pass acxios instance. If not resolved, sharing your store code i can help you more.

**Comment by TheDeveloperTom** [comment]
@pi0 thank you for quick response, really hope you can help me.

I have a problem and I can't grasp how to solve it correctly.

1. I have a js module, it's not a nuxt page or a component, I have created an api folder inside of my nuxt application.   -   http://prntscr.com/giz7wa

2. Inside of this js module, I put some kind of Vue-resource implementation with axios. -  http://prntscr.com/giz8fv

Please have a look at the implementation https://github.com/mzabriskie/axios/issues/894 (the second comment)

And I want to the instance of axios inside of these resources to be the $axios in order to apply the settings from the nuxt.config.js file.

**Comment by pi0** [comment]
@TheDeveloperTom You need a nuxt plugin for that. Because of SSR we can not use global variables (or import/exports) So we can use a plugin for that:

```js
export default function ( { app: { $axios } ) {
   // We can access it
}
```

**Comment by TheDeveloperTom** [comment]
@pi0 Again thanks for quick reply! 
So, If I got you right, I have to create a plugin.
But I still can't grasp how to access then my resources inside components, may you advise me?

**Comment by pi0** [comment]
And there is a inject helper in plugins, (Sorry forgot to mention it)

```js
export default function ( { app: { $axios } , inject) {
   // We can access it
  // Then create our resource instance, let say it is resource.*
  inject('resource', resource)
}
```

Now resource is available in all contexts as `$resource` just like how `$axios` is :)

**Comment by TheDeveloperTom** [comment]
Yes, but the Vue.$axios or this.$axios property is undefined in the module :(

**Comment by pi0** [comment]
How do you access this.$axios ?

**Comment by nzxt** [comment]
This is the question from start. "How need I access nuxt's $axios instance in resource.js". I have the same question.
In my case i have an api.js that was scaffolded by swagger-vue module from backend's swagger.json. In there simply imports axios from axios, uses this new axios instance in exported const-functions and promise returns for each api-call. Maybe define on top of api.js module axios = this.axios?

**Comment by anteriovieira** [comment]
You can provide the instance of axios through a plugin:

```js
// resources.js
export const $axios;

export const User = {
    findById: function (id) {
        ...
        $axios.get(...)
   }
}
...
```

```js
// axios.plugin.js
import resources from '@/path/to/resources'

export default function(ctx, inject) {
if (!ctx.$axios) {
    console.error( 'Please make sure $axios module is added');
  } else {
    resources.$axios = $axios
    inject('resources', resources)
  }
}
```

you can

```js
// store.js
const actions = {
    async getUserById({commit}, payload) {
        const user = await this.$resources.User.findById(payload)
        ...
    }
}
```

or 

```js
// store.js
import {User} from '@/path/to/resources'

const actions = {
    async getUserById({commit}, payload) {
        const user = await User.findById(payload)
        ...
    }
}
```

**Comment by jeck5895** [comment]
Hello I've got a question. My actions is separated from store.js when I try to access this.$axios or context.$axios its undefined.
actions.js
`
fetchRestaurantPhotos: (context, payload) => {
        return new Promise((resolve, reject) => {
         context.$axios.$get(`/web/restaurant/${payload}/photos`)
          .then(response => {
                 context.commit('RestaurantModule/setPhotos', response.data);
                resolve();
             })
        })
    }
`

**Comment by anteriovieira** [comment]
@jeck5895 , did you create the axios plugin?

**Comment by mmitrasish** [comment]
How did you do that? @jeck5895

**Comment by perymimon** [comment]
why because the ssr is can't be import the custom Axios?
if I like to do somthig like that: 
```
import $axios from '@nuxtjs/axios
```
and latter... 
```
const filesAxios = $axios.create({
    baseURL: 'https://www.api.com/files',
    withCredentials: false,
    headers: {
        Authorization: localStorage["auth._token.google"],
    }
})
```

**Comment by inweid** [comment]
i solved this problem like this: https://github.com/nuxt-community/axios-module/issues/28#issuecomment-340743659

**Comment by ubay1** [comment]
just import this in js file
`
import axios from 'axios/index';
`
