### ISSUE TITLE
[proxy] API calls from server are not proxied

### ISSUE THREAD

**Issue by jwahdatehagh** [nuxt-community/modules#113]
I don't know if this is desired, but it seems that API calls are not proxied when called in asyncData from the server side.

```js
{
  async asyncData () {
    let records = []
    try {
      { data } = await axios.get(`/registrations`)
      records = data.records
    } catch (e) {
    }
    return { records }
  }
}
```

When isClient is true, it requests are proxied as expected...

**Comment by pi0** [comment]
Hi. I think this is because if you want proxy to `<proxy>/api/registrations` you have to use either `/api/registration` (absolute) or `registrations`  (relative to base which is `/api/`)
