### ISSUE TITLE
nuxtjs/sitemap - 0.0.3 -- cannot build without external server

### ISSUE THREAD

**Issue by awronski** [nuxt-community/modules#119]
Hi! @NicoPennec 

I get en error when building application with the `npm run build` when the the external server, the one with the api, is off.
```
  nuxt:build Building... +0ms
  [...]
  nuxt:build Generating routes... +5ms
  nuxt:build Building files... +40ms
  build [==                  ] 10%  Error: connect ECONNREFUSED 127.0.0.1:8087
```

During the build the `sitemap` calls the `routes`:
```js
  sitemap: {
    routes: () => sitemapRoutes(app.url, app.api)
  },
```

Could I do something about it?

For example the server can have diffrent API version than the client. I want first build an app, and then restart the server with new api and than start the client app. With this error I cannot do it.

Thanks in advance,

**Comment by NicoPennec** [comment]
This issue is due to `generate: true` option from `nuxt.config.js` file.
The workarround is to remove this param, if you don't use the `generate` nuxt command.

I will update coming soon the module to auto set this option ;-)

Thanks for your feedback 👍

**Comment by awronski** [comment]
@NicoPennec no, I don't use generate. Thanks for the clarification!
