### ISSUE TITLE
Google Analytics not working

### ISSUE THREAD

**Issue by ald890** [nuxt-community/modules#121]
In dev and production mode module is not working, script for analytics is not loading https://www.google-analytics.com/analytics.js

**Comment by pi0** [comment]
Happy your issue resolved :)

**Comment by Slokh** [comment]
Hey I just arrived here from searching. I can't any solutions. Do you mind listing your steps to configure Google Analytics, because I can't seem to figure it out.

**Comment by pi0** [comment]
Hey @Slokh, did you tried using https://github.com/nuxt-community/analytics-module ?

**Comment by Macpeters** [comment]
@pi0 I've been trying to use https://github.com/nuxt-community/analytics-module but it doesn't seem to work.  Maybe the instructions are unclear, but I'm not showing any traffic in GA

**Comment by ald890** [comment]
@Macpeters Did you disable all of chrome extensions which could block GA?

**Comment by Macpeters** [comment]
@ald890 I can go to my site in any browser, or using incognito mode, but according to google analytics, my site hasn't seen any traffic at all

**Comment by ramijames** [comment]
I

> @ald890 I can go to my site in any browser, or using incognito mode, but according to google analytics, my site hasn't seen any traffic at all

I'm having this issue. Anyone have any solutions?

**Comment by ald890** [comment]
@ramijames Adblock ? :D

**Comment by ramijames** [comment]
No, the stats aren't showing up in the analytics dashboard. It's not a local problem.
