### ISSUE TITLE
Markdownit module doesn't work

### ISSUE THREAD

**Issue by iamdubx** [nuxt-community/modules#126]
I installed markdownit module.
First, it asked loader. There's not a single word in documentation that I need some kind of markdown loader. WHY?

Second, I found markdown-loader, tried to install it. You said `seamless integration`. Well, it is not working too. After loader installation I get this errors

```
TypeError: Cannot read property 'loaders' of undefined
  
  - index.js:15 Builder.extendBuild.config
    [markdownit]/[@nuxtjs]/markdownit/index.js:15:20
  
  - utils.js:79 Builder.<anonymous>
    [markdownit]/[nuxt]/lib/common/utils.js:79:8
  
  - client.config.js:223 Builder.webpackClientConfig
    [markdownit]/[nuxt]/lib/builder/webpack/client.config.js:223:31
  
  - builder.js:364 Builder._callee5$
    [markdownit]/[nuxt]/lib/builder/builder.js:364:46
  
  - builder.js:171 Builder._callee$
    [markdownit]/[nuxt]/lib/builder/builder.js:171:16
 ```

Ok. Next, I found a bunch of webpack config settings - https://github.com/nuxt-community/markdownit-loader

I have no idea hot to set it with Nuxt. 
You call this seamless integration?

Also, Nuxtent template is absolutely unusable. I don't understand why you publish all this code.

**Comment by bayssmekanique** [comment]
It's been fixed #125, just waiting for it to be pushed to `npm`.

@pi0, any chance of getting that pushed to `npm`?  I couldn't find a contribution guide so I'm not certain if there is a process to follow for CI or CD?

**Comment by pi0** [comment]
@nuxtjs/markdownit: 1.1.2  released :)

**Comment by iamdubx** [comment]
Thanks for update. What about loader? Do I need it? Do I need to extend webpack config, or this module do this job?

**Comment by pi0** [comment]
@iamdubx It should do it automatically too.

**Comment by iamdubx** [comment]
Confirm, now it's working. Looks like I really started to use this modules in bad times, when Nuxt updating. 
Thank you for support @pi0
