### ISSUE TITLE
documentation for using auth modules

### ISSUE THREAD

**Issue by cahyowhy** [nuxt-community/modules#129]
Can you provide a clear documentation to use auth modules

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/modules/issues/c87">#c87</a>)</em></sub></div>

**Comment by pi0** [comment]
@cahyowhy Sure! But it's pretty outdated now and we are awating for vuex@2.4.0. Please wait for a few couple of days :)

**Comment by anteriovieira** [comment]
You can have access to the auth module at https://github.com/nuxt-community/auth-module

I'm closing this question by considering it was resolved
