### ISSUE TITLE
markdownit-module - list some pages auto

### ISSUE THREAD

**Issue by STnetwork** [nuxt-community/modules#132]
Hi,

Is it possible to do something like that : [Grav - List the last 5 recent blog posts](https://learn.getgrav.org/cookbook/twig-recipes#list-the-last-5-recent-blog-posts), with the markdownit module ?
If it's possible how ? 
If I want to list some pages from some `pages.vue` `<template lang="md">` or by import `md` in a `pages.vue` present in `/pages/example` folder ?

Thanks in advance !

**Edit :** @pi0 maybe you can answer me ? :)

**Comment by STnetwork** [comment]
@pi0 maybe you can answer me ? :)

**Comment by clarkdo** [comment]
Can you please take a look [Nuxt Markdown example](https://github.com/nuxt/nuxt.js/pull/1969) to find out if meet you requirement ?
