### ISSUE TITLE
Why do you use material-design-icons in @nuxt/toast?

### ISSUE THREAD

**Issue by yariksav** [nuxt-community/modules#134]
"material-design-icons": "^3.0.1" takes up a lot of space (45mb) and I don't need this package in my project. I should use raw vue-toaster package instead

**Comment by pi0** [comment]
Hi & thanks for pointing this. Will remove this dep soon.

**Comment by pi0** [comment]
Fixed in `2.3.0` :) Enjoy

**Comment by yariksav** [comment]
Thank you, @pi0
