### ISSUE TITLE
[proposal] module for realtime interactions

### ISSUE THREAD

**Issue by Exitialis** [nuxt-community/modules#142]
I wrote a module that allows you to embed interaction with the echo laravel, and would like to put it out for distribution. With this module, you can do something like the following:

in nuxt.config.js:
```js
laravelEchoSockets: {
    host: process.env.NODE_ENV === 'production' ? 'http://domain.com' : 'http://localhost:3001',
    authInterceptor: (store) => {
      return {
        headers: {
          'Authorization': 'Bearer ' + store.getters['user/token']
        }
      }
    },
    patterns: {
      '{user}': (store) => {
        return store.getters['user/loggedUser'] ? store.getters['user/loggedUser'].id : false
      }
    }
  },
```

It will automaticaly add authorization header, that will be send to your laravel backend. In patterns object you can define patterns, that will be replaced in channels names in socket property. Then, we can write something like that in component or on page:
```js
  export default {
    socket: {
      'private': {
        'App.Models.User.{user}': {
          testEvent: (event) => {
            console.log(event)
          }
        }
      }
    }
  }
```

Now, when event in App.Models.User.{user_id} will be fired, callback will be called. Also, other types of channels are supported. Info about echo can be found at [documentation](https://laravel.com/docs/5.5/broadcasting#receiving-broadcasts)

I'll do pull request if you do not mind. And I apologize for grammatical errors, because english is not my primary language.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/modules/issues/c82">#c82</a>)</em></sub></div>

**Comment by anteriovieira** [comment]
Hi @Exitialis , I saw that you created the module separately, so I'm closing this out by understanding that it has been resolved.

https://github.com/Exitialis/nuxt-laravel-echo
