### ISSUE TITLE
@nuxtjs/proxy: with generate

### ISSUE THREAD

**Issue by husayt** [nuxt-community/modules#144]
Does `@nuxtjs/proxy` work with static websites generated via `nuxt generate`?

**Comment by pi0** [comment]
Hi. I think it won't as current generate implementation directly calls renderer (and thus bypassing any middleware)

**Comment by husayt** [comment]
indeed it doesn't. I just wanted to double check. Will be useful to mention on the page.

Thanks for prompt reply

**Comment by goofcode** [comment]
Any update on this?
