### ISSUE TITLE
Workbox: swURL and swScope as params

### ISSUE THREAD

**Issue by lbineau** [nuxt-community/modules#151]
Hi @pi0 you seems to be the one that maintain workbox plugin :)

If I override swDest option the service worker file will be in a different location but the path to call the worker is different https://github.com/nuxt-community/modules/blob/master/modules/workbox/plugin.js

For the following configuration code
```javascript
modules: [
  ['@nuxtjs/pwa', {
    workbox: {
      swDest: './anotherdist/sw.js'
    }
  }]
]
```

It still generates
```javascript
window.onNuxtReady(() => {
  if (!('serviceWorker' in navigator)) {
    console.warn('serviceWorker is not supported')
    return
  }

  navigator.serviceWorker.register('/sw.js', {
    scope: '/'
  });
})
```

I think it is because swURL and swScope are kind of harcoded with routerBase value
```javascript
  // Register runtime plugin
  this.addPlugin({
    src: path.resolve(__dirname, 'plugin.js'),
    ssr: false,
    options: {
      swURL: fixUrl(`${routerBase}/${swFileName}`),
      swScope: fixUrl(`${routerBase}/`)
    }
  })
```

Could you allow to pass params instead of hard code values? (I want the service worker to be somewhere else)

**Comment by pi0** [comment]
Hey @lbineau :) We have a limitation of service worker spec that paths should be relative to registered `sw.js` file. So if we keep it in `anotherdist/sw.js` it can be enabled for only `anotherdist/*` paths! If this is something you expect then we can add some more options to customize path :)

**Comment by lbineau** [comment]
@pi0 Thank to reply so soon. I didn't know about that limitation but it make sense. Anyway all my resources are in ```anotherdist``` folder so I definitely need thoses options.
Please let me know if I can help.

**Comment by pi0** [comment]
Sure, I'll keep you informed on the progress. Some big updates are coming soon to PWA module & will try to implement an option to specify `sw.js` path.

**Comment by lbineau** [comment]
any news about this issue ?  :)

**Comment by pi0** [comment]
Hey @lbineau. I'm sorry for forgetting about this topic. Sure it is now possible to customize using `swURL`. Please see pwa-module 2.x [docs](https://github.com/nuxt-community/pwa-module#-workbox-module).

**Comment by lbineau** [comment]
Thank you! I'll try it later.
