### ISSUE TITLE
Create new module for milligram

### ISSUE THREAD

**Issue by nikkanetiya** [nuxt-community/modules#152]
Hello,

I would love to create PR submit new module for [milligram](http://milligram.io/) just like bulma. Do you think it will be helpful for the others? If yes then I would love to contribute and will create PR for for the same.

Thanks 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/modules/issues/c93">#c93</a>)</em></sub></div>

**Comment by clarkdo** [comment]
It's good 😸 , go ahead!

**Comment by anteriovieira** [comment]
Hi @nikkanetiya, are you still willing to send the pull request?

**Comment by nikkanetiya** [comment]
@anteriovieira Sorry for late response. Not willing to submit pull request. Used buefy in my last work.
