### ISSUE TITLE
[markdownit] Parsing MD from arbitrary variable 

### ISSUE THREAD

**Issue by maziarz** [nuxt-community/modules#157]
I have been looking at the markdownit module, but unfortunately it does not seem like it offers a way to render markdown from a variable. Normally i use `vue-markdown` to do this, but it does not seem to function with nuxt. Is there a way to render MD from a variable containing the MD code?

I tried to make a hacky solution where i pass down the MD to a child component, but its just rendering it as plain text.

Essentially what i would like to achieve is something like this:

```
<template style="pug">
    div(language="md") {{ mdVariable }}
<template/>

<script>
export default {
    data () {
        return {
            mdVariable: '** This is a header **\n\nSome text'
        }
    }
}
```

**Comment by clarkdo** [comment]
You may take a look at: https://github.com/nuxt/nuxt.js/pull/1969

**Comment by clarkdo** [comment]
you may use `markdown-it` to parse `mdVariable`, such as

```js
import MarkdownIt from 'markdown-it'
const md = new MarkdownIt();
export default {
    data () {
        return {
            mdVariable: md.render('** This is a header **\n\nSome text')
        }
    }
}
```

Maybe it's a better solution to add a `markdown-it` plugin to use same option as `@nuxt/markdown` module, `component` will be like:

```js
export default {
    data () {
        return {
            mdVariable: this.$md('** This is a header **\n\nSome text')
        }
    }
}
```

or

```pug
    div(language="md") {{ $md(mdVariable) }}
```

**Comment by maziarz** [comment]
@clarkdo, thats really awesome. I like the HTML version, that would work perfectly for my use-case!

**Comment by guozhengzhongGit** [comment]
@clarkdo ,it is so cool! i want to know how to use the "HTML verison"?when i write it in template, i get an error"$md is not a function", i use `v-html="$md.render(XXXX)"`is working nice, thanks a lot
