### ISSUE TITLE
@nuxtjs/bulma an example of outdated best practices?

### ISSUE THREAD

**Issue by brianegan** [nuxt-community/modules#158]
Hey hey! Thanks for all the hard work and cool libs. Having fun learning them.

New to nuxt, so just trying to understand a bit better! I wanted to add the `milligram` css framework to my app, and so I copied the example of the @nuxtjs/bulma and made a nuxt-milligram module.

However, I now see that there's a `css` option for `nuxt.config.js` and that might be the better way to add css dependencies. The example on the site even mentions `bulma`! 

What are your thoughts? Are `css` modules like bulma now outdated?

I've updated my own package to point users in the `css` direction: https://gitlab.com/brianegan/nuxt-milligram

**Comment by clarkdo** [comment]
Inside @nuxtjs/bulma, its implementation is  also that add `css` option to config.
I thinks the `module` is a plugin way for other users to integrate some common libs, but directly using `css` in `nuxt.config.js` may be for your app specific libs.

**Comment by brianegan** [comment]
Thanks for the advice!
