### ISSUE TITLE
[google-tag-manager] Not updating on route change

### ISSUE THREAD

**Issue by maziarz** [nuxt-community/modules#159]
I have just installed the `google-tag-manager` module and everything is running smoothly into Google Analytics. Unfortunately the route changes are not being updated in the real-time view. According to the module its something it should be able to do. If i refresh the page while its routed to the new place, it is visible in GA, but between the routes i only see the origin.

**Comment by kubcio** [comment]
Please finally do add that custom event. It would me much easier for us to work @pi0

**Comment by imfaber** [comment]
I solved this by adding a new trigger of type "History change" in GTM.
Hope this helps.

**Comment by maziarz** [comment]
Forgot to close this, i did the exact thing @imfaber.

**Comment by kubcio** [comment]
Guys... its not working properly. Try to set an custom dimension, it'll collect the information from the previous step.

**Comment by maziarz** [comment]
@kubcio did you set the `History Change` in GTM? It basically solved my problem immediately.

**Comment by kubcio** [comment]
In order to catch the correct url im using the history change events. 

The problem is it is a blog page with many authors, so while im trying to pass the author's name of the current article in the pageview tag as a custom dimension, its not possible because it collects the authors name from the previous page.

**Comment by maziarz** [comment]
@kubcio ok, i have not used custom events so if this is an issue i think you need to raise it as a bug.

**Comment by hagemann** [comment]
Sending events is the way to go. Here’s a reference on how a custom Google Analytics plugin does it: https://nuxtjs.org/faq/google-analytics/

Worst case, just use that plugin instead.

**Comment by sowinski** [comment]
Is there any fix to use google analytics with google tag manager and make router changes visible as pageviews?

**Comment by maziarz** [comment]
> Is there any fix to use google analytics with google tag manager and make router changes visible as pageviews?

This is not related to the module but a GTM setup: https://www.analyticsmania.com/post/single-page-web-app-with-google-tag-manager/
