### ISSUE TITLE
[Feature Request] Update bootstrap vue to latest stable version.

### ISSUE THREAD

**Issue by BruceHem** [nuxt-community/modules#162]
It is now stable according to this https://github.com/bootstrap-vue/bootstrap-vue/releases

**Comment by BruceHem** [comment]
Nevermind, I found out that it is now used like the following:

```npm i bootstrap-vue bootstrap@4.0.0-beta.2```

```js
modules: ['bootstrap-vue/nuxt'],
```

**Comment by pi0** [comment]
@BruceHem Thanks for tracking state. We will update instructions soon :)
