### ISSUE TITLE
bootstrap-vue module doesn't exist

### ISSUE THREAD

**Issue by Tekki** [nuxt-community/modules#169]
Awesome-Nuxt [links ](https://github.com/nuxt-community/awesome-nuxt#from-nuxt-communitymodules) to a bootstrap-vue module that should exist in this repo, but it doesn't.

**Comment by pi0** [comment]
Hey. Thanks for the report. Linke is corrected. (https://bootstrap-vue.js.org/docs/#nuxt-js)

**Comment by Tekki** [comment]
Thanks!
