### ISSUE TITLE
font-awesome - include only used icons

### ISSUE THREAD

**Issue by awronski** [nuxt-community/modules#179]
Hi!

I just use couple of icons from the font-awesome. But the module includes everything.
CSS is 30kB + font 75kB. So it is quite big load.

Any suggestion how to include only what I really need?

Thanks in advance,

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/modules/issues/c103">#c103</a>)</em></sub></div>

**Comment by awronski** [comment]
As a workaround I used a [fontello](http://fontello.com/) to extract single icons.

**Comment by anteriovieira** [comment]
The module only includes the css file, unfortunately there is no way to include only some icons.
