### ISSUE TITLE
<nuxt-link> in markdown

### ISSUE THREAD

**Issue by delucis** [nuxt-community/modules#185]
I’m using the `markdown-it` module, and wanted to see if it would be possible to render links as `<nuxt-link>` tags. 

markdown             | html
----------------|----------------------------------------
`[About](/about)` | `<nuxt-link to="/about">About</nuxt-link>`

I managed to do that by setting `md.renderer.rules` for `link_open` and `link_close`, which produces HTML including `<nuxt-link>` tags, but when rendered using `v-html`, Vue/Nuxt doesn’t pick up any included components.

Where would I have to do the markdown rendering in order for those to be processed properly? Or is there an existing solution?

**Comment by zash80** [comment]
I think I ran into the same issue. Having links in markdown that should end up as proper <nuxt-link>. Is there anyone having a solution?
@delucis, can you share your code so i can see how far you Gott? Thanks, M.

**Comment by delucis** [comment]
Hi @zash80 I tried the following on my markdown component:

```js
props: {
  markdown: String
},
computed: {
  renderedMd: function () {
    if (!this.markdown) return undefined
    this.$md.renderer.rules.link_open = function (tokens, idx, options, env, slf) {
      var token = tokens[idx]
      token.attrs = token.attrs.map(attr => {
        if (attr[0] === 'href') attr[0] = 'to'
        return attr
      })
      return '<nuxt-link' + slf.renderAttrs(token) + '>'
    }
    this.$md.renderer.rules.link_close = function () { return '</nuxt-link>' }
    return this.$md.render(this.markdown)
  }
}
```

This renders markdown links as `<nuxt-link>` instead of `<a>` and switches the `href` attribute to be `to`. That’s all fine, but rendering the resulting string using `v-html` won’t compile the contained `<nuxt-link>` elements. I would be interested if you find a solution!

**Comment by zash80** [comment]
Hi @delucis, thanks for sharing your code. With that and with this [post](https://forum.vuejs.org/t/dynamically-compile-router-link/7410) I found a working solution.

`<template>
  <div>
    <component :is="renderedMd"></component>
  </div>
</template>`

`export default {
  props: {
    markdown: String
  },
  computed: {
    renderedMd: function () {
      let rawTemplate = '<div />'
      if (this.markdown) {
        this.$md.renderer.rules.link_open = function (tokens, idx, options, env, slf) {
          var token = tokens[idx]
          token.attrs = token.attrs.map(attr => {
            if (attr[0] === 'href') attr[0] = 'to'
            return attr
          })
          return '<nuxt-link' + slf.renderAttrs(token) + '>'
        }
        this.$md.renderer.rules.link_close = function () { return '</nuxt-link>' }
        rawTemplate = this.$md.render(this.markdown)
      }
      return {
        name: 'DynamicComponent',
        template: rawTemplate
      }
    }
  }
}`

Furthermore I had to add some webpack config into nuxt.config.js build > extend section:
`config.resolve.alias['vue'] = 'vue/dist/vue.js'`

Hope that helps!

**Comment by delucis** [comment]
Awesome! Thanks for sharing — I got it working in no time.

Wish there was a way to avoid using the full Vue library as it adds ~75kb to my build, which seems a lot for some markdown rendering, but I can’t figure out any other way (i.e. the console warning before aliasing `vue` suggests “pre-compiling render functions,” but I don’t how that can be done).

**Comment by Atinux** [comment]
If you guys are interested, this is how we do it on Nuxt.js documentation website: https://github.com/nuxt/nuxtjs.org/blob/master/components/HtmlParser.vue

We bind every link to catch the click event, and if it's a relative link, we simply use `$router.push` :)

**Comment by delucis** [comment]
Thanks @Atinux that’s a much cleaner solution!

**Comment by ManUtopiK** [comment]
@Atinux Your solution works well, but with some regressions.
Vue-router add the classes `router-link-active` and `router-link-exact-active` if the link match the current route.
But especially, nuxt 2.4 bring prefetching, which is not provided by this HtmlParser component.
Is there a way to use nuxt-router or vue-router fonctions directly to parse links?

**Comment by Atinux** [comment]
Great suggestion @ManUtopiK 

I am working on the new Markdown parser that will transform to JSON, so we could directly use `<nuxt-link>` instead of parsing the `<a>` elements :)

**Comment by martinrisseeuw** [comment]
> Great suggestion @ManUtopiK
> 
> I am working on the new Markdown parser that will transform to JSON, so we could directly use `<nuxt-link>` instead of parsing the `<a>` elements :)

Is this something that's still being worked on? Or should I give it a go to implement the solution you guys are currently using for the Nuxt documentation? :)

**Comment by VinuRaj** [comment]
> If you guys are interested, this is how we do it on Nuxt.js documentation website: https://github.com/nuxt/nuxtjs.org/blob/master/components/HtmlParser.vue
> 
> We bind every link to catch the click event, and if it's a relative link, we simply use `$router.push` :)

Looking forward for a working implementation of this.
My V-html data is coming from WordPress REST API and the content has links to internal posts. 

The current link seems to be moved and one i could find [here](https://github.com/nuxt/nuxtjs.org/blob/master/components/commons/HtmlParser.global.vue), seems to be not working for me.

**Comment by d-darwin** [comment]
> If you guys are interested, this is how we do it on Nuxt.js documentation website: https://github.com/nuxt/nuxtjs.org/blob/master/components/HtmlParser.vue
> 
> We bind every link to catch the click event, and if it's a relative link, we simply use `$router.push` :)

The link is broken.

**Comment by MarvinMiles** [comment]
> The link is broken.
https://github.com/nuxt/nuxtjs.org/blob/master/components/commons/HtmlParser.global.vue

**Comment by Atinux** [comment]
I think you can use this module: https://github.com/daliborgogic/nuxt-interpolation

By @daliborgocic

**Comment by febrihidayan** [comment]
@MarvinMiles the link has changed to
[https://github.com/nuxt/nuxtjs.org/blob/master/components/common/AppHtmlParser.vue](https://github.com/nuxt/nuxtjs.org/blob/master/components/common/AppHtmlParser.vue)

**Comment by lampofaladdin** [comment]
> > The link is broken.
> 
> @d-darwin
> https://github.com/nuxt/nuxtjs.org/blob/master/components/commons/HtmlParser.global.vue

The link is broken again...help...
