### ISSUE TITLE
Markdownit injected=true option prevents plugins from running

### ISSUE THREAD

**Issue by janzheng** [nuxt-community/modules#216]
### Version

[latest](https://github.com/modules/releases/tag/latest)

### Reproduction link

[https://github.com/nuxt-community/modules/tree/master/packages/markdownit](https://github.com/nuxt-community/modules/tree/master/packages/markdownit)

### Steps to reproduce

Create a new vue template page with:

<template lang="md">

# This is a title{.bold}

</template>

Nuxt config:

  markdownit: {
    injected: true, // commented out to allow attrs in lang="md" blocks
    use: [
      'markdown-it-attrs',
    ],
  },

### What is expected ?

Expected output: 

<h1 class="bold">This is a title</h1>

### What is actually happening?

Current output when injected is set to true is this:
<h1>This is a title{.bold}</h1>

But plugins still work when using $md.render, so $md.render("# This is a title{.bold}") still outputs expected output.

If injected is set to false, everything works as expected, and the plugins work.

### Additional comments?

I dug through the code and found the culprit. In `@nuxtjs/markdownit/index.js`: 

```
  if (_options.injected === true) {
    delete _options.injected
    // Register plugin
    this.addPlugin({
      src: path.resolve(__dirname, 'plugin.js'),
      fileName: 'markdown-it.js',
      options: _options // <--- this needs an object assignment: Object.assign({}, options, this.options.markdownit)
    })
  }
```

`options: _options` needs an object assignment because in plugin.js, you perform a .shift() on options in the for of loop that gets rid of the plugins and prevents them from being rendered properly. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/modules/issues/c134">#c134</a>)</em></sub></div>

**Comment by sdoering** [comment]
Has anything happened here? I would love to use it and am not sure how to deal with this issue.

**Comment by tvld** [comment]
For me adding classes work nicely with `` npm install --save markdown-it-attrs`` and adding to the options :
```
 use: [
     'markdown-it-attrs'
    ]
```
