### ISSUE TITLE
google-tag-manager does not add noscript to body element.

### ISSUE THREAD

**Issue by Glutnix** [nuxt-community/modules#263]
### What problem does this feature solve?

tracking still takes place when page loaded with javascript turned off

### What does the proposed changes look like?

Module needs to add this immediately after the <body> open tag
```html
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-xxxxxxx&gtm_auth=xxxxxxxxxxxx&gtm_preview=xxxx&gtm_cookies_win=x" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/modules/issues/c151">#c151</a>)</em></sub></div>

**Comment by Glutnix** [comment]
I'm prepared to try write a PR for this. Let me know if a PR is likely to be accepted.

**Comment by manniL** [comment]
Go ahead :relaxed:

**Comment by shavidzet** [comment]
Any updates?

**Comment by LeBenLeBen** [comment]
@derz Would you have time to open a merge request to this repo? I'd love to see that feature merged.

**Comment by ladislavsulc** [comment]
This would be great. Please, merge this. Thank you.

**Comment by raWINce** [comment]
Can you please update the npm repository?

**Comment by akagamina** [comment]
any solution about this thread?

**Comment by LeBenLeBen** [comment]
I might be wrong but according to the history it should be available since version 2.3.0 published a couple of days ago

**Comment by raWINce** [comment]
Yes, it has been published. I am already using it

**Comment by jubeiam** [comment]
This implementation is not valid according to google robots.
When I wget my index page there is not `noscript` tag under the `body` tag
