### ISSUE TITLE
 @nuxtjs/google-tag-manager TypeError: The 'request' argument must be string. Received type object

### ISSUE THREAD

**Issue by VarghaSabee** [nuxt-community/modules#299]
I have this error 
![Capture](https://user-images.githubusercontent.com/36417378/61533161-4ab26900-aa2c-11e9-96a2-9d3706da2e80.PNG)

**Comment by sebastianjung** [comment]
For me it was fixed by checking the syntax in the nuxt.config.js. 

Somehow my editor would add some parantheses.

got it working like so:

```
modules: [
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    [
      '@nuxtjs/google-gtag',
      {
        id: 'UA-XXXXXXX-1', // required,
        debug: false // enable to track in dev mode
      }
    ]
  ]
```
