### ISSUE TITLE
Nuxtjs/toast: How to pass message to globally configured toast module

### ISSUE THREAD

**Issue by Panksi** [nuxt-community/modules#329]
How to pass message to globally configured toast module?

In my nuxt file I have:
` modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/toast',
    '@nuxtjs/eslint-module'
  ],
  toast: {
    position: 'top-right',
    register: [ // Register custom toasts
      {
        name: 'my_error',
        options: {
          type: 'error',
          theme: 'bubble',
          duration: '7000'
        }
      }
    ]
  },`

and I tried passing the message with:

`updateApplication(fields) {
      ApplicationService.updateApplication(this.application.app_id, fields)
        .catch((e) => this.$toast.global.my_error(e))
    },`

what am I missing here?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/modules/issues/c174">#c174</a>)</em></sub></div>

**Comment by davidsandoz** [comment]
Based on the [vue-toasted documentation](https://github.com/shakee93/vue-toasted#custom-toast-registration), it looks like one has to provide an object with a `message` attribute instead of a string.

=> `this.$toast.global.my_error({message: e})`

However, as I was trying to do the same, even this solution didn't work for me. Can you let me know if it does for you?

**Comment by davidsandoz** [comment]
I also see that you provided the duration as string whereas it should be provided as a number (`7000` instead of `'7000'`).

**Comment by davidsandoz** [comment]
Ha, reading the documentation more carefully myself, I realized that we actually have to set a function for `message`, when we register.

So if you want to keep `this.$toast.global.my_error(e)`, then you have to register your custom toast like this:
```
register: [ // Register custom toasts
      {
        name: 'my_error',
        message: message => message
        options: {
          type: 'error',
          theme: 'bubble',
          duration: 7000
        }
      }
    ]
```
