### ISSUE TITLE
Unit / E2E Testing

### ISSUE THREAD

**Issue by jsonberry** [nuxt-community/modules#33]
I just started digging into adding unit test functionality to a Nuxt project. Because `vue-loader` is in use it looks like my path forward is to work on creating a setup like this: https://vue-loader.vuejs.org/en/workflow/testing.html

I thought I perhaps would put work into making a PR for Nuxt to try and include support for unit testing, but then I just came across this modules repo.

Questions for the community:
1. Is there already something in the works for providing unit testing support in Nuxt?
2. If not, would it be best to start working on a Nuxt module for unit testing vs. making a PR againt Nuxt core?

**Comment by jsonberry** [comment]
There does seem to be a backlog item posted by @Atinux here https://github.com/nuxt/nuxt.js/projects/1?card_filter_query=test

**Comment by alidcastano** [comment]
+1, it'd be awesome to have a module that could easily setup testing. I'd def be best as a module IMO since people use diff testing utilities.

**Comment by alidcastano** [comment]
finally created it a testing utility myself :) https://github.com/studbits/nuxt-jest-puppeteer

**Comment by jsonberry** [comment]
@alidcastano awesome!
