### ISSUE TITLE
Yandex Metrica not working

### ISSUE THREAD

**Issue by artemmelnik** [nuxt-community/modules#339]
![image](https://user-images.githubusercontent.com/30805374/72070314-ef35a980-32f1-11ea-8000-623e45520ced.png)

The counter for the robot is displayed incorrectly!

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/modules/issues/c181">#c181</a>)</em></sub></div>

**Comment by altynbek07** [comment]
@artemmelnik I have same problem. Have you solved this problem?

**Comment by VitaliyDemchuk** [comment]
When the module is turned on with the counter code in the console, there is nothing. The tag is used to check the operation of the counter (?_ym_debug=1). The site is launched in production.
