### ISSUE TITLE
Cannot add module @nuxtjs/axios to project

### ISSUE THREAD

**Issue by yariksav** [nuxt-community/modules#38]
After install and add module 
```
modules: [
    '@nuxtjs/axios'
]
```

npm nuxt crashed with message

**[nuxt] Unable to resolve module @nuxtjs/axios
[SyntaxError: Unexpected token {]**

when I remove this line '@nuxtjs/axios', the project starts correctly. Where is mistake?

**Comment by pi0** [comment]
Would you please provide full version of your `nuxt.config.js` ?

**Comment by yariksav** [comment]
it crashed event at not filled config file,  example
```
module.exports = {
  modules: [
    '@nuxtjs/axios'
  ]
}
```
I have tried to remove line by line in file nuxt.config.js

**Comment by pi0** [comment]
Are you sure also using latest nuxt version _1.0.0-alpha.4_ ? That's strange problem and i can reproduce it .Please double check installed version and cleaning up `.nuxt`  & `node_modules` before run. 

https://mica-bulb.glitch.me/
https://glitch.com/edit/#!/mica-bulb?path=nuxt.config.js:3:18

**Comment by yariksav** [comment]
Yes, nuxt version is latest: 1.0.0-alpha.4.
I've copied you package.json to new folder, runned npm install and copied nuxt.config.js
```
{
  "name": "nuxt-hello",
  "scripts": {
    "start": "nuxt"
  },
  "dependencies": {
    "nuxt": "^1.0.0-alpha.4",
    "@nuxtjs/axios": "latest"
  }
}
```
```

module.exports = {
  modules: [
    '@nuxtjs/axios'
  ]
}
```
And result was same:
S:\web\test\nuxt-test>npm run start

```
> nuxt-hello@ start S:\web\test\nuxt-test
> nuxt

[nuxt] Unable to resolve module @nuxtjs/axios
[SyntaxError: Unexpected token {]
```

Perhaps this depends of operation system> My os is Win7

**Comment by yariksav** [comment]
Success! I was because of old node vesrion. I've updated it to latest version 6.11.0 and all is done! THank you very match and my apologises!

**Comment by gilzonme** [comment]
I am using 16 and it happens to me. I don't think it is due to node version (for me).
