### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/modules#381]
I noticed @pi0 made this: https://github.com/nuxt/modules/issues/12 also the usual plugin page gives a 404.

**Comment by simplenotezy** [comment]
https://github.com/nuxt-community/modules/tree/master/packages/bulma

**Comment by pi0** [comment]
Hi @simplenotezy. Actually some packages here are stalled or have better active alternatives to be listed in modules.nuxtjs.org . Bulma is the case that has alternative. Other modules (like `yandex`) will be slowly moved out-of mono repo

**Comment by simplenotezy** [comment]
Okay thanks @pi0 😊 This page links to a 404 page though: https://www.npmjs.com/package/@nuxtjs/bulma -> https://github.com/nuxt/modules/tree/master/packages/bulma (under "Homepage")
