### ISSUE TITLE
Problem with nuxt generate

### ISSUE THREAD

**Issue by ald890** [nuxt-community/modules#44]
`nuxt generate`
`[nuxt] Generating...`
`[nuxt] Unable to resolve module @nuxtjs/axios`
`{ Error: Cannot find module '@nuxtjs/axios'`

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/modules/issues/c14">#c14</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey. Are you sure `@nuxtjs/axios` dependency is installed in `package.json`? Technically there shouldn't be any difference between generate and build.

**Comment by ald890** [comment]
Yes dependency is installed, and when I run `npm run dev` it works, but when I run `nuxt generate` for production version I have an error.

**Comment by gdomiciano** [comment]
Hey Guys, 
I've fixed it using `@nuxt/axios` as a _dependency_ instead of a _dev dependency_ in my **package.json**

So, now my `package.json` looks like:
``` json
"dependencies": {
    "@nuxtjs/axios": "^2.3.0",
    "@nuxtjs/proxy": "^1.1.1",
    "nuxt": "^1.0.0-alpha.4",
    "vue-loader": "^12.2.1",
    "vue-meta": "^1.0.4",
    "vue-router": "^2.5.3",
    "vue-ssr-html-stream": "^2.2.0",
    "vue-style-loader": "^2.0.0"
  },
  "devDependencies": {...},
```
instead of:
``` json

"dependencies": {
    "nuxt": "^1.0.0-alpha.4",
    "vue-loader": "^12.2.1",
    "vue-meta": "^1.0.4",
    "vue-router": "^2.5.3",
    "vue-ssr-html-stream": "^2.2.0",
    "vue-style-loader": "^2.0.0"
  },
  "devDependencies": {
    "@nuxtjs/axios": "^2.3.0",
    "@nuxtjs/proxy": "^1.1.1",
    ...
  },
```

**Comment by anteriovieira** [comment]
Thanks @gdomiciano
