### ISSUE TITLE
[@nuxtjs/bootstrap-vue] override link control to use nuxt-link

### ISSUE THREAD

**Issue by pimlie** [nuxt-community/modules#45]
As nuxt.js uses a `<nuxt-link/>` component instead of `<router-link/>`, shouldn't the `link` component in `@nuxtjs/bootstrap-vue` module use `is="nuxt-link"` instead of `is="router-link"`?

As far as I see at the moment it doesnt matter much as `<nuxt-link/>` does not provide extra functionality. Also this can probably not be fixed without changes in `bootstrap-vue`?

**Comment by pi0** [comment]
Hi. Actually, links are complicated than this. BootstrapVue also has a <b-link> helper component. Will reopen issue open when nuxt-link has more functionality then deciding the best way for integration. BTW right now usage is safe and equal :)

**Comment by pimlie** [comment]
As I understand that this repository is in full-swing development, maybe it would be an idea to add a ToDo/Known issue (or similar) section to the README of a modules for things like this (and #43 with the icon module).

Hopefully that would prevent other people from repeating these questions :)

**Comment by pi0** [comment]
We are adding a modules section to nuxt.js website. Good idea mentioning such todos in each modules' page.
