### ISSUE TITLE
[proposal] add a plugin helper package

### ISSUE THREAD

**Issue by pimlie** [nuxt-community/modules#52]
Would you accept a PR for a `@nuxtjs/plugin-helper` package which will at least contain debug/info functions? At the moment most logging by the plugins are done by calling `console.log`, but it would be nice if we use the same `debug` package as `nuxtjs` uses so all output during build is nicely formatted. 

My idea would be to export functions that always add a 'plugin:' text to the logging. And maybe we choose a different colour then nuxt's blue? This way we have an uniform and recognizable way of logging. 

```js
const isProd = process.env.NODE_ENV === 'production'

if (isProd) {
  const log = () => () => null
  const error = () => () => null

  module.exports = { log, error }
} else {
  const Debug = require('debug')

  let instances = {}

  const log = (plugin_name) => {
    if (!instances['log_' + plugin_name]) {
      const log = Debug('plugin:' + plugin_name)
      log.enabled = true
      log.color = 5
      instances['log_' + plugin_name] = log
    }
    return instances['log_' + plugin_name]
  }

  const error = (plugin_name) => {
    if (!instances['err_' + plugin_name]) {
      const error = Debug('plugin:' + plugin_name)
      error.enabled = true
      error.color = 1
      instances['err_' + plugin_name] = error
    }
    return instances['err_' + plugin_name]
  }

  module.exports = { log, error }
}
```
and usage would be:
```js
module.exports.meta = require('./package.json')
const debug = require('@nuxtjs/plugin-utils').log(module.exports.meta.name)
const error = require('@nuxtjs/plugin-utils').error(module.exports.meta.name)

log('information about what the plugin is doing during build') // printed in purple
error('oops, something went wrong') // printed in red
```
I am using currently something similar for `rfg-icon`, but think we could benefit if we centralize the logging :)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/modules/issues/c44">#c44</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. That's a nice idea indeed i was also thinking of a helper package for plugins! I suggest some improvements to basic idea:
- Having a more general name like `plugin-utils`
- Create debug instances out of arrow functions once, for performance.
  - Using some template condition to remove dependency of `Debug` package from production builds. This is important as can add unwanted package size. (We can create a noop handler like `() => () => null` to remove debug)

**Comment by pimlie** [comment]
I updated both example codes, would something like that be ok? I used a simple `if (process.env.NODE_ENV === 'production') {` so code is removed through tree shaking. Not sure how you could get template conditions to work here while keeping a package that works both in prod as in dev.

**Comment by anteriovieira** [comment]
I'm closing this issue by understanding that the module was added as discussed.
