### ISSUE TITLE
Should export a function

### ISSUE THREAD

**Issue by ImadBoumzaoued** [nuxt-community/modules#53]
Getting this error with nuxt@1.0.0-alpha.4

```[nuxt] Module [@nuxtjs/name, [object Object]] should export a function```

**Comment by pi0** [comment]
@ImadBoumzaoued Would you please check this file version? `node_modules/nuxt/package.json` It may be due to incorrect install. Also please provide your `nuxt.cofing.js`

**Comment by ImadBoumzaoued** [comment]
Yup you're right it was still using nuxt@1.0.0-alpha.2 even after i did ```rm -rf node_modules```

Thanks a lot @pi0 👍
