### ISSUE TITLE
Does not support 'all' / Performing multiple concurrent requests

### ISSUE THREAD

**Issue by silverbackdan** [nuxt-community/modules#55]
An example is provided on axios github:
```js
function getUserAccount() {
  return axios.get('/user/12345');
}

function getUserPermissions() {
  return axios.get('/user/12345/permissions');
}

axios.all([getUserAccount(), getUserPermissions()])
  .then(axios.spread(function (acct, perms) {
    // Both requests are now complete
  }));
```

With this implementation $axios.all is not defined. It may be nice to implement this in the same way as the other main methods if possible? Or is it advisable just to import axios for this purpose?

**Comment by pi0** [comment]
Hi. If you look at axios source code, here is the implementation. [here](https://github.com/mzabriskie/axios/blob/master/lib/helpers/spread.js#L23) and [here](https://github.com/mzabriskie/axios/blob/master/lib/axios.js#L43). They are just simple wrappers over Promise :)

```js
// Expose all/spread
axios.all = function all(promises) {
 return Promise.all(promises);
};

// Axios.speard
module.exports = function spread(callback) {
   return function wrap(arr) {
     return callback.apply(null, arr);
 };
```

I thing that because of a legacy support. While nuxt supports modern ES6 out of the box so we can use simple approach:

```js
// In asyncData or fetch

// Parallel requests
const [ acct, perms ] = await Promise.all([getUserAccount(), getUserPermissions()])

// Sequential requests
const acct = await getUserAccount()
const perms = await getUserPermissions()
```

**Comment by silverbackdan** [comment]
Thanks @pi0 - very helpful!

**Comment by azulkipli** [comment]
> Hi. If you look at axios source code [here](https://github.com/mzabriskie/axios/blob/master/lib/helpers/spread.js#L23) and [here](https://github.com/mzabriskie/axios/blob/master/lib/axios.js#L43). They are just simple wrappers over Promise :)
> 
> ```js
> // Expose all/spread
> axios.all = function all(promises) {
>  return Promise.all(promises);
> };
> 
> // Axios.speard
> module.exports = function spread(callback) {
>    return function wrap(arr) {
>      return callback.apply(null, arr);
> };
> ```
> 
> I think that is because of an old legacy support problem. While nuxt supports modern ES6 out of the box so we can use simple approach:
> 
> ```js
> // In asyncData or fetch
> 
> // Parallel requests
> const [ acct, perms ] = await Promise.all([getUserAccount(), getUserPermissions()])
> 
> // Sequential requests
> const acct = await getUserAccount()
> const perms = await getUserPermissions()
> ```

Hi @pi0 so in nuxt vuex store module how to use these function?
