### ISSUE TITLE
Axios - Possible to extend the setToken functionality?

### ISSUE THREAD

**Issue by silverbackdan** [nuxt-community/modules#56]
Is there a way the setToken functionality could be extended to `setHeader` ? `setToken` could still exist but essentially call the `setHeader` method:

Instead of:
```js
// Set requests token
function setToken (token, type, scopes = 'common') {
  if(!Array.isArray(scopes)) {
    scopes = [scopes]
  }
  scopes.forEach(scope => {
    if (!token) {
      delete this.defaults.headers[scope].Authorization;
      return
    }
    this.defaults.headers[scope].Authorization = (type ? type + ' ' : '') + token
  })
}
```

It could be:
```js
// Sets a common header
function setHeader (name, value, scopes = 'common') {
  if(!Array.isArray(scopes)) {
    scopes = [scopes]
  }
  scopes.forEach(scope => {
    if (!value) {
      delete this.defaults.headers[scope][name];
      return
    }
    this.defaults.headers[scope][name] = value
  })
}
// Set requests token
function setToken (token, type, scopes = 'common') {
    value = !token ? null : (type ? type + ' ' : '') + token
    setHeader('Authorization', value, scopes)
}
```

The reason I ask is because I'm implementing a CSRF/XSRF token. The API and Website domains are different which limits my ability to get the cookies from the API on the client-side as the headers are stripped.

To make the cookies more secure, it's better to have them as httpOnly I've read - so instead of using the built-in axios header and cookie XSRF functionality and just setting the cookie in the middleware if `isServer` is true (with an axios get request), I was wanting to get the value and set the default header. I can't seem to just modify the 'defaults' of the axios object, so instead right now I have to set the default headers into my store and then read them again when I want to use them. Also I'm wanting to add the header `X-Requested-With: XMLHttpRequest` to every request.

Am I just going about this the wrong way, or would this functionality be useful?

**Comment by pi0** [comment]
@silverbackdan, To be honest, I'm still confused with your use case but feel free making PR for `setHeader` (Also don't forget to add little docs :D)

**Comment by silverbackdan** [comment]
My use case was ridiculous, convoluted and pointless :P I do think it'd be useful to add custom headers in some cases though where an API may require it. I'll get the code above into a PR with docs hopefully this week or over the weekend.

For the XSRF token, it was much better to adjust the API to accept the token in a cookie, that way the value is never exposed to JS and can have httpOnly and secure flags. Also the API can sign the cookie. Thanks!

**Comment by pi0** [comment]
Thanks. BTW it may be still useful as we don't always have change access to API. (Using third party apis for example)

**Comment by silverbackdan** [comment]
I think we're all good with this one now. Thanks @pi0

**Comment by silverbackdan** [comment]
@pi0 Just wondering when you may be ready for a version bump?

**Comment by pi0** [comment]
soon. There are two open issues for axios remaining.
