### ISSUE TITLE
axios setToken

### ISSUE THREAD

**Issue by OrangeXC** [nuxt-community/modules#57]
when I use `this.$axios.setToken()`,It's work

but I want setToken in `check-auth.js`  router middle

```
import { getUserFromCookie, getUserFromLocalStorage } from '~/utils/auth'

export default function ({ isServer, store, req }) {
  // If nuxt generate, pass this middleware
  if (isServer && !req) return
  const loggedUser = isServer ? getUserFromCookie(req) : getUserFromLocalStorage()

  if (loggedUser) {
    store.commit('user/SET_TOKEN', loggedUser)
    store.$axios.setToken(loggedUser.token)
  }
}
```

the `store.$axios.setToken` or `app.$axios.setToke` is not work

my request header don't have auth token

what's the better method when I reload website can use axios.setToken

**Comment by uptownhr** [comment]
How are you storing your token? I currently use js-cookie to store in cookie and read back.

**Comment by awronski** [comment]
@OrangeXC Check this:
https://github.com/nuxt-community/modules/issues/89
