### ISSUE TITLE
API Documentation 

### ISSUE THREAD

**Issue by sebastianmacias** [nuxt-community/modules#58]
Is there a full nuxt-modules API documentation somewhere?

I would like to implement some modules but besides the official modules I can't find any docs. For instance I would like to know how to extend routes from a module.

Thanks,

**Comment by pi0** [comment]
Hey. Thanks for your intetest, Unfortounatly docs are not ready yet to extend using modules but will be provided soon after `rc` release of nuxt :) BTW for extending routes you can use `this.extendRoutes({...})` inside module. [here](https://github.com/nuxt-community/content-module/blob/master/lib/module.js#L44) is an example. Please let me know if anything needed before docs are ready.

**Comment by pi0** [comment]
Modules guide is now live! https://nuxtjs.org/guide/modules

**Comment by sebastianmacias** [comment]
@pi0 excellent news. Thanks!
