### ISSUE TITLE
custom modules

### ISSUE THREAD

**Issue by wormen** [nuxt-community/modules#60]
Tell me how the user file modules should be placed in the file structure of the project?

**Comment by pi0** [comment]
Hi. Usually modules are being published as npm packages so they can be reused by both your company and others in projects. But you can create small local modules in a `modules` directory of your project then referencing to them with something like `modules: [ '~/modules/auth.js' ]`

**Comment by wormen** [comment]
I somehow can get data from the current `store`?
Or only from isolated, [how here](https://github.com/nuxt-community/modules/tree/master/modules/auth)?
