### ISSUE TITLE
Using markdownit module, each plugin is replaced with null

### ISSUE THREAD

**Issue by chrisvfritz** [nuxt-community/modules#63]
With this config:

``` js
modules: [
  '@nuxtjs/pwa',
  [
    '@nuxtjs/markdownit', {
      preset: 'default',
      linkify: true,
      breaks: true,
      preprocess: function (markdownIt, source) {
        // do any thing
        return source
      },
      use: [
        require('markdown-it-container'),
        require('markdown-it-attrs')
      ]
    }
  ]
]
```

I'm getting the error:

```
Module build failed: TypeError: Cannot read property 'apply' of null
    at MarkdownIt.use (/...project.../node_modules/markdown-it/lib/index.js:496:9)
    at /...project.../node_modules/markdownit-loader/lib/core.js:66:18
    at Array.forEach (native)
    at Object.module.exports (/...project.../node_modules/markdownit-loader/lib/core.js:62:15)
```

The problem is that sometime before these options are passed to the module, each item in the `use` array has been replaced by `null`, resulting in `[null, null]`. MarkdownIt doesn't like `null` plugins, so we get the error.

**Comment by pi0** [comment]
Hey @chrisvfritz . Thanks for spotting this bug, actually there seems root problem backs to how vue-loader works, which magically makes `opts.use[]` children to null.and it works fine with `import '~/docs/foobar.md') (This is not a key conflict renaming to something like `plugins` still gets error)
So as a quick workaround i'm going to add lazy require support for `markdown-it` loader. Will keep this thread updated.

**Comment by pi0** [comment]
The problem should now resolve with the latest release. I've also updated [readme](https://github.com/nuxt-community/modules/tree/master/modules/markdownit).

**Comment by chrisvfritz** [comment]
Woohoo! Thanks. 🙂

**Comment by phikhi** [comment]
@pi0 @chrisvfritz I have the same error while trying to load markdown-it-attrs plugin.

Error message : `Module build failed: TypeError: Cannot read property 'apply' of null`

Here is my nuxt.config.js

```
markdownit: {
    preset: 'default',
    linkify: true,
    breaks: true,
    use: [
      require('markdown-it-attrs')
    ]
  },
```

I'm using these packages 
```
nuxt@1.4.0
@nuxtjs/markdownit@1.2.0
markdown-it-attrs@1.2.1
```

Is there anything that I am missing here ?
