### ISSUE TITLE
@nuxtjs/google-analytics: [nuxt] Module [[object Object]] should export a function

### ISSUE THREAD

**Issue by AdmiralPotato** [nuxt-community/modules#64]
Please forgive me if this is a complete duplicate of #27, but while the solution to that problem may have to update the version of nuxt, I'm actually getting this same problem on what looks like up to date versions.

Steps to reproduce on a completely empty folder:
```
npm init
--followed by filling out the form--
npm install --save nuxt
npm install --save @nuxtjs/google-analytics
```

`package.json` was edited to add the `dev` script, and looks like this:
```
{
  "name": "erase_plz",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "nuxt"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@nuxtjs/google-analytics": "^1.0.0",
    "nuxt": "^1.0.0-alpha.5"
  }
}
```

`nuxt.config.js` is created with the following content:
```
module.exports = {
	modules: ['@nuxtjs/google-analytics', { ua: 'UA-XXXXXXX-X' }]
};
```

So I run `npm run dev`, and this is the output:

```
$ npm run dev

> erase_plz@1.0.0 dev C:\temp\erase_plz
> nuxt

[nuxt] Module [[object Object]] should export a function

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! erase_plz@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the erase_plz@1.0.0 dev script 'nuxt'.

```

The pain point seems to be the `modules: ['@nuxtjs/google-analytics', { ua: 'UA-XXXXXXX-X' }]` line - because without it, I am at least given the ``"Couldn't find a `pages` directory. Please create one under the project root"`` message, which would get me to the rest of the application on other projects.

Am I doing something wrong? Am I missing something? Is there a chance that it's my LTS node version, and the `engine` property isn't specified in the `@nuxtjs/google-analytics` `package.json` file?

**Comment by pi0** [comment]
Hi. Thanks for your complete description Would you please explicitly remove -r `node_modules` and `package-lock.json` and test again? Your above error seems from a common bug with npm.

**Comment by AdmiralPotato** [comment]
While I can't seem to find any trace of a `package-lock.json` file in the `erase_plz` folder, I did run the following:

```
$ rm -rf node_modules
$ npm install
$ npm run dev
```

...which still yields the same error as above. Have I missed something? Is there a global `package-lock.json` that needs to be erased?

**Comment by pi0** [comment]
Nope that lock file is created only with npm5... Is your project public on github or can we somehow access to it ?

**Comment by AdmiralPotato** [comment]
It's so simple that it doesn't warrant a repo - I'll attach a zip of the two files.
Just run `npm install` on it when you get it.

- erase_plz/
  - package.json
  - nuxt.config.js

[erase_plz.zip](https://github.com/nuxt-community/modules/files/1149705/erase_plz.zip)

Not sure if it was easy to see earlier, but I am running `node v6.11.0`, `npm  v3.10.10`. I guess the success condition is getting the ``"Couldn't find a `pages` directory. Please create one under the project root"`` error.

**Comment by AdmiralPotato** [comment]
Looks like wrapping the config contents in a function solved the problem for me.

`nuxt.config.js` contents now look like this:
```
module.exports =  function(){
	return {
		modules: ['@nuxtjs/google-analytics', { ua: 'UA-XXXXXXX-X' }]
	};
};
```

I'm not yet sure if this will break anything else, but it has me up and running for now at least. So perhaps this is a documentation issue, and the install guide needs to show the `nuxt.config.js` contents wrapped in a function?
