### ISSUE TITLE
axios/plugin.js - $axios.setToken errors

### ISSUE THREAD

**Issue by awronski** [nuxt-community/modules#65]
Hi!

I try to set token in the store action:

```javascript
 actions: {
    async setAuthToken ({ state, commit }, { authToken, $axios }) {
      $axios.setToken(authToken, 'Bearer')
      [...]
  }
```

But there is an error ```ReferenceError: value is not defined```
About this line of code:
https://github.com/nuxt-community/modules/blob/master/modules/axios/plugin.js#L68

But even if I fix it then there is error here:
https://github.com/nuxt-community/modules/blob/master/modules/axios/plugin.js#L63

```Cannot read property 'defaults' of undefined```.

**Comment by pi0** [comment]
Hi. Thanks for the report. This seems from a recent refactor for adding `setHeader` function. Please upgrade to `@nuxtjs/axios:2.2.1`

**Comment by awronski** [comment]
Thanks for the quick fix!
