### ISSUE TITLE
Question - Serving dynamic xml files using modules

### ISSUE THREAD

**Issue by awronski** [nuxt-community/modules#66]
Hi!

Is it possible to use modules to server dynamic files? For example generating sitemap.xml?

Now I use nuxt as middleware with express. But maybe there is solution to use modules to extends router to do it with standalone nuxt?

**Comment by pi0** [comment]
Hi. Sure we can. We can even do this without need to modules just using `serverMiddleware`, option in `nuxt.config.js`, each server middleware can be an express/connect compatible middleware like this:
```js
module.exprots = (req, res, next) => {

  // Call to next if middleware chain should be continues
  next();
}
```

Or if you want only handle special root: 
```js
module.exports = {
 path: '/api/foo',
 handler: (req, reply, next) => { next() } 
}
```

**Comment by NicoPennec** [comment]
Hi @awronski 
I'm working on the same topic!
You can check my PR https://github.com/nuxt-community/modules/pull/69

**Comment by awronski** [comment]
@NicoPennec Hi! Great! I will check it and give you know if I have any sugestions
