### ISSUE TITLE
Question: how to enable service worker in PWA template

### ISSUE THREAD

**Issue by Darkside73** [nuxt-community/modules#71]
I'm trying to use ```@nuxtjs/pwa``` module. It generates manifest file for me. But there are no registered service workers. And when I click on "Add to homescreen" link from devtools it throws error:
```
Site cannot be installed: no matching service worker detected. You may need to reload the page, or check that the service worker for the current page also controls the start URL from the manifest
```
Tested on https://github.com/nuxt-community/pwa-template

**Comment by pi0** [comment]
@Darkside73 Is this problem anymore?

**Comment by Darkside73** [comment]
I'll check out  workaround #75 and let you know. Thanks

**Comment by Darkside73** [comment]
It works with @nuxtjs/workbox 1.1.1
