### ISSUE TITLE
@nuxtjs/workbox: service workers fetch resources by wrong URL

### ISSUE THREAD

**Issue by Darkside73** [nuxt-community/modules#75]
All nuxt bundles are served by URLs starting with ```/_nuxt```. But service workers try to fetch them without this prefix. I think it should work with default options.
BTW: I've tried to use ```modifyUrlPrefix``` to fix:
```js
modifyUrlPrefix: {
  '/': '/_nuxt/'
}
```
but no success

**Comment by pi0** [comment]
Hi. Yes known issue with latest workbox upgrade, I'm currently working on it please let me know if any success :))

**Comment by pi0** [comment]
Found it!!
```js
modifyUrlPrefix: {
  '': '/_nuxt/'
}
```

**Comment by pi0** [comment]
Should be fixed with `workbox@1.1.0`.

**Comment by pi0** [comment]
Ahh another issue regexes are broken too!

**Comment by pi0** [comment]
Should be fixed with `"@nuxtjs/workbox": 
"^1.1.1"`. Also working with offline too:
Demo: https://nuxt-pwa.glitch.me
https://glitch.com/edit/#!/nuxt-pwa?path=package.json:9:4
