### ISSUE TITLE
[workbox] XHR in offline mode

### ISSUE THREAD

**Issue by Darkside73** [nuxt-community/modules#79]
I'm thinking about full offline support for nuxt powered application. The thing missed out is the following: nuxt page on client-side routing is trying to fetch fresh data over XHR. In offline mode it leads to application error. But we can use SSR generated data instead to display page correctly.
What the best way to solve this issue and is it the workbox module responsibility at all?

**Comment by pi0** [comment]
Hi. 

> In offline mode it leads to application error. But we can use SSR generated data instead to display pag

If SSR mode is enabled, then all fetches are done from server side too and should be cached with Network first strategy. So latest response should be available in workbox cache. Also for dynamic API requests suggest using proxy to serve them on same domain too `/api/*` so they will be cached too with workbox :)

**Comment by Darkside73** [comment]
Does not work in my case. All requests are going to the same domain with ```/api/``` prefix. Is there any special requirements for HTTP client? I'm still use vue-resource initialized via my custom nuxt plugin

> SSR mode is enabled

where I suppose to enable it?

**Comment by pi0** [comment]
It should be already enabled! Would you please explain more about use case? I mean what behavior is expected and what is happening now?

**Comment by Darkside73** [comment]
I have nuxt 1.0-alpha application with pwa module enabled. SW is working correctly as I see in devtools (```activated and is running```). In ```fetch``` method vuex store is populated by remote data fetched with vue-resource.
If application is offline and we navigate to page with mentioned ```fetch``` method then nuxt renders 500 error page and errors appears in browser console:
```
Failed to load resource: net::ERR_INTERNET_DISCONNECTED
/api/v1/search to load resource: net::ERR_INTERNET_DISCONNECTED
The FetchEvent for "https://myapp.com/api/v1/search" resulted in a network error response: an object that was not a Response was passed to respondWith().
vendor.bundle.3215ec6….js:26 GET https://myapp.com/api/v1/search net::ERR_FAILED
(anonymous) @ vendor.bundle.3215ec6….js:26
<----- skipped ----->
vendor.bundle.3215ec6….js:26 XHR failed loading: GET "https://myapp.com/api/v1/search".
(anonymous) @ vendor.bundle.3215ec6….js:26
<----- skipped ----->
search:1 Uncaught (in promise) wt {…}
logo.47c6bca.png Failed to load resource: net::ERR_INTERNET_DISCONNECTED
```

**Comment by Darkside73** [comment]
Maybe the repo with example could be helpful?

**Comment by pi0** [comment]
I got it, thanks for the info. So can't we use [window.navigator.onLine](https://github.com/nuxt-community/pwa-template/blob/master/template/pages/index.vue#L38) for this check and prevent calling fetch? Also, did you tried native `window.fetch` for XHR requests?

**Comment by pi0** [comment]
**UPDATE** [here](https://css-tricks.com/serviceworker-for-offline/#article-header-id-8) mentioned about service workers should work with XHR too:

> The fetch event fires whenever a page controlled by this service worker requests a resource. This isn’t limited to fetch or even XMLHttpRequest. Instead, it comprehends even the request for the HTML page on first load, as well as JS and CSS resources, fonts, any images, etc. Note also that requests made against other origins will also be caught by the fetch handler of the ServiceWorker

**Comment by Darkside73** [comment]
I didn't try any special handler for offline mode. Using callback for ```fetch``` event sounds good to me. But it looks like a boilerplate a bit. Maybe it should be part of this module?

**Comment by Darkside73** [comment]
Update after some experiments: XHR is cached out of the box, so no additional code is required.
Good job ;)

**Comment by chabib** [comment]
@Darkside73 Do you use pwa module? Since it contains workbox modules, I think caching should work out of the box too, but it is not, despite using native fetch method
@pi0 where might do I do wrong?

**Comment by pi0** [comment]
@chabib Please consider that your website should be HTTPS for everything to get working :)

**Comment by Darkside73** [comment]
@chabib does service worker registered in your app?

**Comment by chabib** [comment]
@pi0 localhost should be treated the same way as https, right?
@Darkside73 yes, i checked it in dev tools
So, I have nuxt run in localhost through some port, and also run api server through other port.
Is it related this?

>Also for dynamic API requests suggest using proxy to serve them on same domain too /api/* so they will be cached too with workbox :)

I dont really understand above statement
