### ISSUE TITLE
Example : Adding a directory from a module to a plugin.

### ISSUE THREAD

**Issue by rwatts3** [nuxt-community/modules#80]
Greetings, 
Is it or would it be possible to register a directory, from my module into the end user's pages directory?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/modules/issues/c48">#c48</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Yep, it's possible but you have to manually register all pages (IE no pages directory structure is forced anymore for using with modules) this way we have more flexibility.

**Comment by anteriovieira** [comment]
I am closing this question by understanding that the doubt has been answered.
