### ISSUE TITLE
axios: How should I set up Token correctly?

### ISSUE THREAD

**Issue by seekcx** [nuxt-community/modules#81]
I tried to set the token in middleware:
```js
store.$axios.setToken(token)
```
But there is a problem.

If the page is rendered from the server, the request on the page will not be accompanied by Authorization unless I jump to a new page, Let the middleware run in the browser once.

**Comment by uptownhr** [comment]
I'm currently handling this in nuxtserverinit

**Comment by seekcx** [comment]
@uptownhr Thank you very much for your tips, Can you give me a little simple example?

**Comment by seekcx** [comment]
I have not noticed that you have made some suggestions in the #89 , close the issue, focus on the discussion.
