### ISSUE TITLE
using axios module from fetch

### ISSUE THREAD

**Issue by uptownhr** [nuxt-community/modules#88]
With the axios module, it is currently expected that axios is passed into actions. However, I'm not seeing a way to get the app.$axios instance from within the fetch method.

It would be awesome if the axios module can be imported from the store to easily solve this issue.

Anyone know of a workaround this for the time being?

**Comment by uptownhr** [comment]
Reading the source, I was able to find that $axios is available from store.
https://github.com/nuxt-community/modules/blob/master/modules/axios/plugin.js#L171

```
app.$axios = axios
  ctx.$axios = axios
  if (store) {
    store.$axios = axios
  }
```

One note: I've tried using $axios in context but it is empty. Why is this?

**Comment by pi0** [comment]
Hi. About `import from store` it is impossible as now vue-server-renderer doesn't uses something like sandbox for performance reasons. So everything should be passed within exported functions. Also context of `fetch` and `asyncData` is the same. You can access and pass $axios instance using `async fetch({ app: {$axios}})`.

For easier usage and availability within store, we've already made a PR for Vuex and with it's next release we can use axios in actions using `this.$axios` Just like normal `.vue` files :) (This code is just prepared for that enhancement)

**Comment by BjornMelgaard** [comment]
fk, cant wait new release of vuex

**Comment by imShara** [comment]
No changes about `this.$axios`?

```js
export default {
  async fetch({ app: {$axios}}) {
    console.log($axios) // Axios object
  }
}
```

```js
export default {
  async fetch ({ store, params }) {
    console.log(this.$axios) // Undefined
  }
}
```

```js
created: function() {
  console.log(this.$axios) // Axios object
}
```

**Comment by ChrisDillinger** [comment]
`export default {
  async fetch ({ $axios }) {
    console.log($axios) // =>  { [Function: wrap]
                                      //           request: [Function: wrap],
                                      //           delete: [Function: wrap],
                                      //           get: [Function: wrap],
                                      //           ...etc
  }
}`
