### ISSUE TITLE
[axios] this.$delete is overlapping vue's this.$delete

### ISSUE THREAD

**Issue by BjornMelgaard** [nuxt-community/modules#90]
because of this I have real error, like this one:
[plugin is using vue's $delete](https://github.com/fergaldoyle/vue-form/blob/7cad2558515928232931dd8e40d98460ca5cd3e7/src/components/validate.js#L119), but it is overlapped by axios $delete

I suggest to remove $delete, $post ... aliases  and leave access to them only through $axios

**Comment by BjornMelgaard** [comment]
@pi0, can you push changes into npm, please?

**Comment by pi0** [comment]
Sure. As it was a breaking change it is now released under `@nuxtjs/axios`:3.0.0

**Comment by pi0** [comment]
Also as a note, $ helpers will be added as $axios attrs again in next releases for easier axios usage:
```js
// Current usage
let posts = (await this.$axios.get('posts').data

// Easier usage
let posts = await this.$axios.$get('posts')
```

I don't think they may make any conflict under $axios scope :)

**Comment by BjornMelgaard** [comment]
ok, I think I can leave with that)

P.S. error was fixed, tnks
