### ISSUE TITLE
`this.$get is not a function` on @nuxtjs/axios 3.0.1

### ISSUE THREAD

**Issue by JermeyYann** [nuxt-community/modules#93]
- index.vue
```javascript
this.$get(url).then((res) => {
  if (res.data.success) {
    this.blogs = res.data.value;
    this.page.total = this.blogs.totalCount;
  } else {
    this.$message({
      showClose: true,
      message: res.data.message,
      type: 'error'
    });
  }
})
```

- result

![image](https://user-images.githubusercontent.com/13900367/28589766-07900f74-71b2-11e7-879f-e3b138d97d2c.png)

**Comment by pi0** [comment]
Hi. Sorry, this was a breaking change we have decided to avoid conflicts (#90) :( You have to use `this.$axios.get` instead.
